/**
 * Hardcoded fallback representatives for NY-10 (Empire State Building area).
 * Used when OpenStates geo API is unavailable (502/503).
 */
export const FALLBACK_REPS = [
  {
    bioguideId: 'S000148',
    fecId: 'S8NY00282',
    openStatesId: 'ocd-person/f7bcfe68-1f2d-4f2c-b8c4-d1893f8b27d4',
    name: 'Chuck Schumer',
    party: 'D',
    office: 'Senator, New York',
    level: 'federal',
    stateCode: 'NY',
    photoUrl: 'https://theunitedstates.io/images/congress/225x275/S000148.jpg',
    website: 'https://www.schumer.senate.gov',
    votes: null, votesDataSource: null, finance: null, conflict: null, influenceScore: null, errors: [],
  },
  {
    bioguideId: 'G000555',
    fecId: 'S8NY00289',
    openStatesId: 'ocd-person/a1a2b3c4-0000-0000-0000-000000000001',
    name: 'Kirsten Gillibrand',
    party: 'D',
    office: 'Senator, New York',
    level: 'federal',
    stateCode: 'NY',
    photoUrl: 'https://theunitedstates.io/images/congress/225x275/G000555.jpg',
    website: 'https://www.gillibrand.senate.gov',
    votes: null, votesDataSource: null, finance: null, conflict: null, influenceScore: null, errors: [],
  },
  {
    bioguideId: 'G000586',
    fecId: 'H0IL07048',
    openStatesId: 'ocd-person/a1a2b3c4-0000-0000-0000-000000000002',
    name: 'Daniel Goldman',
    party: 'D',
    office: 'Representative, NY-10',
    level: 'federal',
    stateCode: 'NY',
    photoUrl: 'https://theunitedstates.io/images/congress/225x275/G000586.jpg',
    website: 'https://goldman.house.gov',
    votes: null, votesDataSource: null, finance: null, conflict: null, influenceScore: null, errors: [],
  },
  {
    bioguideId: null,
    fecId: null,
    openStatesId: 'ocd-person/ny-state-demo-01',
    name: 'Brad Hoylman-Sigal',
    party: 'D',
    office: 'State Senator, District 47 (New York)',
    level: 'state',
    stateCode: 'NY',
    photoUrl: null,
    website: 'https://www.nysenate.gov/senators/brad-hoylman',
    votes: null, votesDataSource: null, finance: null, conflict: null, influenceScore: null, errors: [],
  },
  {
    bioguideId: null,
    fecId: null,
    openStatesId: 'ocd-person/ny-state-demo-02',
    name: 'Tony Simone',
    party: 'D',
    office: 'State Assembly Member, District 75 (New York)',
    level: 'state',
    stateCode: 'NY',
    photoUrl: null,
    website: 'https://nyassembly.gov/mem/Tony-Simone',
    votes: null, votesDataSource: null, finance: null, conflict: null, influenceScore: null, errors: [],
  },
];
